// <auto-generated />
using System;
using InnoShop.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InnoShop.Domain.Migrations
{
    [DbContext(typeof(InnoShopContext))]
    partial class InnoShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InnoShop.Domain.Models.Locality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id")
                        .HasName("PK__Localiti__3214EC07601BC24A");

                    b.ToTable("Localities");
                });

            modelBuilder.Entity("InnoShop.Domain.Models.ProdAttrib", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("ProdId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ProdAttr__3214EC07905CC3BF");

                    b.HasIndex("ProdId");

                    b.ToTable("ProdAttribs");
                });

            modelBuilder.Entity("InnoShop.Domain.Models.ProdType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id")
                        .HasName("PK__ProdType__3214EC070A05AE8A");

                    b.ToTable("ProdTypes");
                });

            modelBuilder.Entity("InnoShop.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuyerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(7, 2)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("ProdTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Public")
                        .HasColumnType("bit");

                    b.Property<bool>("Sold")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Products__3214EC074E540A36");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ProdTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("InnoShop.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("LocalityId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC072D6A52E8");

                    b.HasIndex("LocalityId");

                    b.HasIndex("UserTypeId");

                    b.HasIndex(new[] { "UserName" }, "UQ__Users__5E55825B2B853D4C")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InnoShop.Domain.Models.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id")
                        .HasName("PK__UserType__3214EC0709A91F01");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("InnoShop.Domain.Models.ProdAttrib", b =>
                {
                    b.HasOne("InnoShop.Domain.Models.Product", "Prod")
                        .WithMany("ProdAttribs")
                        .HasForeignKey("ProdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ProdAttri__ProdI__0D0FEE32");

                    b.Navigation("Prod");
                });

            modelBuilder.Entity("InnoShop.Domain.Models.Product", b =>
                {
                    b.HasOne("InnoShop.Domain.Models.User", "Buyer")
                        .WithMany("ProductsBuyer")
                        .HasForeignKey("BuyerId")
                        .HasConstraintName("FK_Users_Buyers");

                    b.HasOne("InnoShop.Domain.Models.ProdType", "ProdType")
                        .WithMany("Products")
                        .HasForeignKey("ProdTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Products__ProdTy__084B3915");

                    b.HasOne("InnoShop.Domain.Models.User", "User")
                        .WithMany("ProductsUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Products_Users");

                    b.Navigation("Buyer");

                    b.Navigation("ProdType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InnoShop.Domain.Models.User", b =>
                {
                    b.HasOne("InnoShop.Domain.Models.Locality", "Locality")
                        .WithMany("Users")
                        .HasForeignKey("LocalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Users__LocalityI__056ECC6A");

                    b.HasOne("InnoShop.Domain.Models.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__UserTypeI__047AA831");

                    b.Navigation("Locality");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("InnoShop.Domain.Models.Locality", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("InnoShop.Domain.Models.ProdType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InnoShop.Domain.Models.Product", b =>
                {
                    b.Navigation("ProdAttribs");
                });

            modelBuilder.Entity("InnoShop.Domain.Models.User", b =>
                {
                    b.Navigation("ProductsBuyer");

                    b.Navigation("ProductsUser");
                });

            modelBuilder.Entity("InnoShop.Domain.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
